{{ config(materialized='table')}}

WITH CTE AS (
    SELECT
        TO_TIMESTAMP(START_TIME) AS START_TIME,
        DATE(TO_TIMESTAMP(START_TIME)) AS DATE_START_TIME,
        HOUR(TO_TIMESTAMP(START_TIME)) AS HOUR_START_TIME,
        DAYNAME(TO_TIMESTAMP(START_TIME)) AS DAYNAME,
        {{get_day_type('START_TIME')}} AS DAY_TYPE,
        DAY(TO_TIMESTAMP(START_TIME)) DAY_START_TIME,
        YEAR(TO_TIMESTAMP(START_TIME)) YEAR_START_TIME,
        MONTH(TO_TIMESTAMP(START_TIME)) MONTH_START_TIME,
        CAST(TO_TIMESTAMP(START_TIME) AS TIME) ONLY_TIME,
        {{get_station('START_TIME')}} AS STATION_OF_DAY
    FROM {{source('demo', 'BIKES')}}
)
SELECT 
*
FROM CTE