{{ config(materialized='table')}}

WITH CTE AS (
    SELECT
        TO_TIMESTAMP(START_TIME) AS START_TIME,
        DATE(TO_TIMESTAMP(START_TIME)) AS DATE_START_TIME,
        HOUR(TO_TIMESTAMP(START_TIME)) AS HOUR_START_TIME,
        DAYNAME(TO_TIMESTAMP(START_TIME)) AS DAYNAME,
        CASE
            WHEN DAYNAME(TO_TIMESTAMP(START_TIME)) IN ('SAT', 'SUN') THEN 'WEEKEND'
            ELSE 'BUSINESS'
        END AS DAY_TIPE,
        DAY(TO_TIMESTAMP(START_TIME)) DAY_START_TIME,
        YEAR(TO_TIMESTAMP(START_TIME)) YEAR_START_TIME,
        MONTH(TO_TIMESTAMP(START_TIME)) MONTH_START_TIME,
        CAST(TO_TIMESTAMP(START_TIME) AS TIME) ONLY_TIME,
        CASE
            WHEN MONTH(TO_TIMESTAMP(START_TIME)) IN (12,1,2) THEN 'SUMMER'
            WHEN MONTH(TO_TIMESTAMP(START_TIME)) IN (3,4,5) THEN 'AUTUMN'
            WHEN MONTH(TO_TIMESTAMP(START_TIME)) IN (6,7,8) THEN 'WINTER'
            ELSE 'SPRING'
        END AS STATION_OF_DAY
    FROM {{source('demo', 'BIKES')}}
)
SELECT 
*
FROM CTE